---

- name: >
     Executing Anisble Module "{{task}}"
  include_tasks:
    file: "{{task}}.yml" #|join('')}}"
  # vars:
  #   items:
  #     - "{{(task == 'ping')|ternary('ping.yml,'')}}"
      #- "{{(task2 == 'shell')|ternary('shell.yml,'')}}"