---

- name: >
     Executing Anisble Module "{{task}}"
  include_tasks:
    #file: "{{task}}.yml" 
    file: "{{item}}"
  loop: 
    - "{{ (task == 'ping')|ternary('ping.yml', '') }}"
    - "{{ (task == 'shell')|ternary('shell.yml', '') }}"
  ignore_errors: true

  