---
- name: Administrator playbook
  hosts: "{{ hosts | default('all') }}"
  gather_facts: true
  vars:
    empty_vars: { group:'',  
  roles:
    - common/parameters/shared/defaults
  # environment: 

  pre_tasks:
  
  tasks:
    - name: Block 1 
      block:
        - name: <-> 
          debug:
            msg: "Administrator playbook"
        - name: Include Role
          include_role: 
            name: "{{ role | default('no_role') }}"


    # - name: Include Role
    #   include_role: 
    #     name: "{{ role | default('no_role') }}"
      
      