---
- name: Administrator playbook
  hosts: "{{ hosts | default('all') }}"
  gather_facts: true
  # vars:
  #   #hosts_empty: { group:'', env:''} 
  #   group: "{{(group != '' | ternary ({{group}}|upper, ''))}}"
  #   env: "{{(env != '' | ternary ({{env}}|upper, ''))}}"
    

  # roles:
  #   - common/parameters/shared/defaults
  # environment: 

  pre_tasks:
  
  tasks:
    - name: Block 1 
      block:
        - name: <-> 
          debug:
            msg: "Administrator playbook"
        - name: Include Role
          include_role: 
            name: "{{ role | default('ping') }}"
    # - name: Access Control
    #   block:
      


    # - name: Include Role
    #   include_role: 
    #     name: "{{ role | default('no_role') }}"
      
      