---
- name: Administrator playbook
  hosts: "{{ hosts | default('all') }}"
  gather_facts: true
  become: yes
  vars_files:
    - secret.yml
  tasks:
    - name: Block 1 
      block:
      - name: <-> 
        debug:
          msg: "Administrator playbook"
    


    - name: Include Role
      include_role: 
        name: "{{ role | default('no_role') }}"
      