---
- name: Engineer playbook
  hosts: "{{ hosts | default('all') }}"
  gather_facts: true
  become: yes
  vars_files:
    - secret.yml
  tasks:
    - name: Block 1 
      block:
      - name: <-> 
        debug:
          msg: "Engineer playbook"
    

    - name: Executing common tasks
      include_role:
        name: common
    - name: Include Role
      include_role: 
        name: "{{ role | default('no_role') }}"