---
- name: Parent playbook (Administarator)
  hosts: all
  gather_facts: true
  become: yes
  vars_files:
    - secret.yml
  tasks:
    - name: Block 1 
      block:
      - name: Ansible shell 
        #shell: whoami #"{{shell}}"
        include_role: shell
        become: yes
        register: shellout
      - name: debug shell out
        debug:
          msg: "{{shellout}}"



  

        

# - name: Update db servers
#   hosts: databases
#   remote_user: root

#   tasks:
#   - name: Ensure postgresql is at the latest version
#     ansible.builtin.yum:
#       name: postgresql
#       state: latest
#   - name: Ensure that postgresql is started
#     ansible.builtin.service:
#       name: postgresql
#       state: started